### ISSUE TITLE
Publish new version on ansible-galaxy

### ISSUE THREAD

**Issue by rommsen** [weareinteractive/ansible-openssl#12]
Could you please publish 1.8.0 to ansible galaxy?
I am getting errors because of the not quoted variables in manage.yml in 1.7.0.

Just wanted to make a PR until I saw that you already fixed it in this repo.

Thanks

**Comment by franklinkim** [comment]
Sure, done. Let me know if 1.8.0 still has some quote issues. cheers

**Comment by rommsen** [comment]
Looks good. Thanks a lot for the quick reply!
