### ISSUE TITLE
Tags and master don't match

### ISSUE THREAD

**Issue by reelsense** [weareinteractive/ansible-openssl#15]
* New release, committed to master 4 months ago. 
* Look at master, says last update 9 months ago...

https://github.com/weareinteractive/ansible-openssl/releases

I can see the files [at this URL](https://github.com/weareinteractive/ansible-openssl/tree/aa4294b4a657055b292b758b55ea03e41ff5de67), but they were [never merged to master](https://github.com/weareinteractive/ansible-openssl/tree/master).

**Comment by franklinkim** [comment]
THX, somehow I didn't push to master (shame on me) ... just pushed
